export const BRAND = {
  name: "19 HOURS FITNESS",
  shortName: "19 HOURS",
  tagline: "Where Transformation Becomes a Lifestyle.",
  eyebrow: "VIRAR WEST · FITNESS CLUB",
  location: "Virar West, Maharashtra, India",
  fullAddress: "Plot No. 201–202, Varkhana Bhavan, Viva College Road, Virar West, Maharashtra 401303",
  hours: "Mon – Sat: 5:30 AM – 11:00 PM | Sun: 7:00 AM – 8:00 PM",
  phone: "+91 83906 79679",
  whatsappNumber: "918390679679",
  whatsappUrl: "https://wa.me/918390679679?text=Hi%2019%20Hours%20Fitness%2C%20I%20would%20like%20to%20book%20a%20free%20trial%20session.",
  mapsUrl: "https://maps.google.com/?q=19+Hours+Fitness+Virar+West+Maharashtra",
  instagramUrl: "https://instagram.com/19hoursfitness",
  instagramHandle: "@19HOURSFITNESS",
};

export const NAV_LINKS = [
  { name: "About", href: "#about" },
  { name: "Experience", href: "#experience" },
  { name: "Transformations", href: "#transformations" },
  { name: "Training", href: "#training" },
  { name: "Trainers", href: "#trainers" },
  { name: "Gallery", href: "#gallery" },
  { name: "Location", href: "#location" },
];

export const EXPERIENCE_PANELS = [
  {
    number: "01",
    title: "STRENGTH",
    category: "HEAVY IRON & BIOMECHANICS",
    description: "Structured progressive overload, Olympic lifting platforms, calibrated plates, and precision biomechanical racks engineered for pure power.",
    image: "/images/experience/strength.jpg",
  },
  {
    number: "02",
    title: "CROSSFIT",
    category: "HIGH-OUTPUT CONDITIONING",
    description: "Dynamic functional training arena with climbing ropes, kettlebell bays, assault sleds, and high-intensity metabolic conditioning.",
    image: "/images/experience/crossfit.jpg",
  },
  {
    number: "03",
    title: "PERSONAL TRAINING",
    category: "1-ON-1 COACHING",
    description: "Bespoke periodization, movement screening, and relentless accountability under certified strength and conditioning specialists.",
    image: "/images/experience/pt.jpg",
  },
  {
    number: "04",
    title: "CARDIO",
    category: "ENDURANCE ENGINE",
    description: "Air bikes, curved treadmills, Concept2 rowers, and skiergs configured for targeted VO2 max enhancement and fat oxidation.",
    image: "/images/experience/cardio.jpg",
  },
  {
    number: "05",
    title: "RECOVERY",
    category: "STEAM & MOBILITY",
    description: "Thermal steam facilities, contrast recovery zones, and guided mobility protocols to accelerate cellular repair between sessions.",
    image: "/images/experience/recovery.jpg",
  },
];

export const TRANSFORMATION_DATA = {
  title: "REAL PEOPLE. REAL TRANSFORMATIONS.",
  subtitle: "Every metric earned through disciplined execution, proper nutrition, and structured programming.",
  client: "Verified Member Case",
  program: "16-Week Body Recomposition",
  stats: [
    { value: "-2.85 KG", label: "TOTAL WEIGHT" },
    { value: "-1.0%", label: "BODY FAT" },
    { value: "+1.2%", label: "LEAN MASS" },
  ],
  beforeImage: "/images/transformation/before.jpg",
  afterImage: "/images/transformation/after.jpg",
};

export const TRAINING_GOALS = [
  {
    id: "strength",
    title: "STRENGTH",
    subtitle: "Absolute force production and barbell mastery.",
    description: "Develop maximum strength across squat, bench, deadlift, and overhead press with intelligent RPE and percentage-based periodization.",
    image: "/images/training/strength.jpg",
    tags: ["Powerlifting", "Progressive Overload", "Form Mastery"],
  },
  {
    id: "muscle",
    title: "MUSCLE GAIN",
    subtitle: "Hypertrophy-focused volume and mechanical tension.",
    description: "Targeted mind-muscle isolation, optimal volume distribution, and specialized intensity techniques to stimulate maximum muscular hypertrophy.",
    image: "/images/training/muscle.jpg",
    tags: ["Hypertrophy", "Volume Cycles", "Pumping Biomechanics"],
  },
  {
    id: "fatloss",
    title: "FAT LOSS",
    subtitle: "Accelerated metabolic expenditure and lean retention.",
    description: "High-density resistance workouts paired with targeted metabolic finishers to burn stubborn fat while preserving hard-earned muscle tissue.",
    image: "/images/training/fatloss.jpg",
    tags: ["Metabolic Conditioning", "Caloric Deficit Protocol", "EPOC"],
  },
  {
    id: "conditioning",
    title: "CONDITIONING",
    subtitle: "Athletic agility, speed, and cardiovascular stamina.",
    description: "Multi-planar functional drills, turf sled work, and explosive plyometrics designed to build real-world athletic durability.",
    image: "/images/training/conditioning.jpg",
    tags: ["Work Capacity", "Agility", "Aerobic Engine"],
  },
];

export const GALLERY_IMAGES = [
  {
    src: "/images/facilites/envirnoment/functional-arena.png",
    alt: "19 Hours Fitness Functional Turf and CrossFit Rigs",
    caption: "Functional Turf & CrossFit Arena",
    tag: "ZONE 01 • TURF & RIGS",
    location: "VIRAR WEST",
  },
  {
    src: "/images/facilites/envirnoment/free-weights-dumbbell-rack.png",
    alt: "Jordan Free Weights and Dumbbell Section with Ambient Neon",
    caption: "Heavy Dumbbell Arsenal",
    tag: "ZONE 02 • FREE WEIGHTS",
  },
  {
    src: "/images/facilites/envirnoment/olympic-lifting-platform.png",
    alt: "Olympic Lifting Platform and Power Rack Station with Barbell",
    caption: "Olympic Lifting Platform",
    tag: "ZONE 03 • POWER CAGE",
  },
  {
    src: "/images/facilites/envirnoment/strength-machines-area.png",
    alt: "Life Fitness Selectorized Machine Strength Suite",
    caption: "Life Fitness Strength Suite",
    tag: "ZONE 04 • SELECTORIZED",
  },
  {
    src: "/images/facilites/envirnoment/cable-station-sprint-track.png",
    alt: "Dual Cable Pulldown Station and Indoor Sprint Track",
    caption: "Cable Motion & Sprint Track",
    tag: "ZONE 05 • AGILITY LANE",
  },
  {
    src: "/images/facilites/envirnoment/cardio-elliptical-zone.png",
    alt: "Cardio Endurance Deck with Ellipticals and Natural Light",
    caption: "Cardio Endurance Deck",
    tag: "ZONE 06 • CARDIO DECK",
  },
  {
    src: "/images/facilites/envirnoment/member-lounge-reception.png",
    alt: "19 Hours Fitness Member Lounge and Athlete Consultation Suite",
    caption: "Member Lounge & Consultation",
    tag: "ZONE 07 • SANCTUARY",
    location: "VIRAR WEST",
  },
];

export const REVIEWS = [
  {
    quote: "The atmosphere here is completely different from ordinary gyms in Virar. No clutter, top-tier equipment, and trainers who actually understand biomechanics and progressive overload.",
    author: "Verified Member",
    source: "Google Review",
    rating: 5,
    tag: "STRENGTH MEMBER",
  },
  {
    quote: "Joined for the 16-week transformation program. The structured diet and coaching accountability helped me drop body fat while keeping my bench and squat numbers climbing.",
    author: "Verified Member",
    source: "Google Review",
    rating: 5,
    tag: "TRANSFORMATION CLIENT",
  },
  {
    quote: "Clean, dark aesthetic, spacious crossfit floor, and steam recovery that makes daily training sustainable. 19 Hours Fitness is easily the finest athletic facility in Virar West.",
    author: "Verified Member",
    source: "Google Review",
    rating: 5,
    tag: "CROSSFIT ATHLETE",
  },
];

export const INSTAGRAM_POSTS = [
  {
    url: "https://www.instagram.com/p/Dcyi85fiWiz/",
    src: "/images/instagram/post-12.jpg",
    alt: "30 Days Transformation Challenge 1st Winner Award",
    title: "🏆 30 Days Challenge — 1st Winner",
    tag: "TRANSFORMATION",
    type: "post",
  },
  {
    url: "https://www.instagram.com/p/DcyhutFi2LY/",
    src: "/images/instagram/post-9.jpg",
    alt: "30 Days Transformation Challenge 2nd Winner Award",
    title: "🥈 30 Days Challenge — 2nd Winner",
    tag: "TRANSFORMATION",
    type: "post",
  },
  {
    url: "https://www.instagram.com/p/DcyfUUmiPUk/",
    src: "/images/instagram/post-11.jpg",
    alt: "30 Days Transformation Challenge 3rd Winner Award",
    title: "🥉 30 Days Challenge — 3rd Winner",
    tag: "TRANSFORMATION",
    type: "post",
  },
  {
    url: "https://www.instagram.com/reel/Dc0NLfRtjIs/",
    src: "/images/instagram/post-5.jpg",
    alt: "Personal Training Session with Coach Ravikant Khadtare",
    title: "Discipline > Motivation • Coach Ravikant",
    tag: "COACH REEL",
    type: "reel",
  },
  {
    url: "https://www.instagram.com/reel/Db0HkurtACt/",
    src: "/images/instagram/post-1.jpg",
    alt: "19 Hours Fitness Athlete Heavy Deadlift Session",
    title: "Heavy Deadlift PR Day",
    tag: "STRENGTH REEL",
    type: "reel",
  },
  {
    url: "https://www.instagram.com/reel/DcfTUljIDHX/",
    src: "/images/instagram/post-3.jpg",
    alt: "Athlete Heavy Barbell Back Squat Set",
    title: "Barbell Back Squats Focus",
    tag: "SQUAT REEL",
    type: "reel",
  },
  {
    url: "https://www.instagram.com/reel/DdL2S5vou7J/",
    src: "/images/instagram/post-8.jpg",
    alt: "19 Hours Fitness Post-Workout Pump Reel",
    title: "The Post-Workout Pump",
    tag: "TRAINING REEL",
    type: "reel",
  },
  {
    url: "https://www.instagram.com/reel/DcyLXqMsTyi/",
    src: "/images/instagram/post-4.jpg",
    alt: "Workout Intensity and Persistence Reel",
    title: "Pure Grit & Persistence",
    tag: "MOTIVATION REEL",
    type: "reel",
  },
  {
    url: "https://www.instagram.com/reel/DcMLw_bM5Oi/",
    src: "/images/instagram/post-2.jpg",
    alt: "19 Hours Fitness Gym Athlete Focus and Intensity",
    title: "Night Shift Focus & Grind",
    tag: "COMMUNITY REEL",
    type: "reel",
  },
  {
    url: "https://www.instagram.com/reel/Dc1ejGNoHlp/",
    src: "/images/instagram/post-6.jpg",
    alt: "Member Transformation and Determination Reel",
    title: "Scars Build Strength",
    tag: "MEMBER REEL",
    type: "reel",
  },
  {
    url: "https://www.instagram.com/reel/Dc2GpwVhZnp/",
    src: "/images/instagram/post-7.jpg",
    alt: "High Energy Conditioning and Fitness Workout",
    title: "Athletic Conditioning Flow",
    tag: "WORKOUT REEL",
    type: "reel",
  },
  {
    url: "https://www.instagram.com/reel/DdeGtgKvc4B/",
    src: "/images/instagram/post-10.jpg",
    alt: "Athlete Workout Journey at 19 Hours Fitness",
    title: "Daily Consistency In Action",
    tag: "ATHLETE REEL",
    type: "reel",
  },
];

export const TRAINERS = [
  {
    id: "ravikant-khadtare",
    number: "01",
    name: "Ravikant Khadtare",
    role: "Founder & Athletic Conditioning Specialist",
    badge: "FOUNDER & OWNER",
    isOwner: true,
    discipline: "Cardio Engine & Agility",
    image: "/images/trainers/ravikant-khadtare.png",
    ogImage: "/images/trainers/og/ravikant-khadtare-card.jpg",
    ogPhoto: "/images/trainers/og/ravikant-khadtare.jpg",
    quote: "Endurance is built when you think you're done, but keep pushing anyway.",
    bio: "Founder and Owner of 19 Hours Fitness, Ravikant is the visionary behind Virar West's premier athletic and transformation club. With over a decade of elite coaching experience, he established 19 Hours Fitness to redefine the training landscape—uniting high-performance biomechanics, explosive athletic conditioning, and an uncompromising standard of discipline under one roof. His personalized coaching protocols push the cardiovascular engine to its absolute limits, forging athletes who possess unyielding stamina, physical power, and ironclad mental resilience.",
    certifications: ["Founder & Head Coach", "Certified Functional Strength Coach (CFSC)", "Advanced Cardiovascular Conditioning Specialist"],
    experience: "10+ Years",
    instagram: "https://instagram.com/19hoursfitness",
  },
  {
    id: "harpinder-singh",
    number: "02",
    name: "Harpinder Singh",
    role: "Strength & Resistance Coach",
    badge: "COACH 02 · CADRE",
    discipline: "Barbell Mastery & Muscle Gain",
    image: "/images/trainers/harpinder-singh.png",
    ogImage: "/images/trainers/og/harpinder-singh-card.jpg",
    ogPhoto: "/images/trainers/og/harpinder-singh.jpg",
    quote: "True strength is the discipline to master the basics, relentlessly.",
    bio: "Harpinder is a master of the barbell. His philosophy is rooted in progressive overload and flawless biomechanics. He strips away the noise and focuses on heavy, compound movements that drive pure mechanical tension and hypertrophy. If your goal is to add serious slabs of dense muscle while ensuring joint integrity, Harpinder’s structured periodization is your blueprint.",
    certifications: ["Strength and Conditioning Specialist (CSCS)", "Hypertrophy Programming Certification"],
    experience: "8+ Years",
    instagram: "https://instagram.com/19hoursfitness",
  },
  {
    id: "swapnil-gothal",
    number: "03",
    name: "Swapnil Gothal",
    role: "Strength & Performance Coach",
    badge: "COACH 03 · CADRE",
    discipline: "Powerlifting & Biomechanics",
    image: "/images/trainers/swapnil-gothal.png",
    ogImage: "/images/trainers/og/swapnil-gothal-card.jpg",
    ogPhoto: "/images/trainers/og/swapnil-gothal.jpg",
    quote: "Force production is an exact science. Train with precision.",
    bio: "Swapnil brings a hyper-analytical approach to strength sports. As a powerlifting specialist, he meticulously dissects the squat, bench, and deadlift to optimize leverage and force transfer. His coaching goes beyond simply moving weight; it’s about understanding the nervous system, refining movement patterns, and peaking for maximum absolute strength. His athletes don't just lift heavy—they lift perfectly.",
    certifications: ["Elite Powerlifting Coach", "Biomechanics & Human Movement Specialist"],
    experience: "12+ Years",
    instagram: "https://instagram.com/19hoursfitness",
  },
  {
    id: "nilesh-patekar",
    number: "04",
    name: "Nilesh Patekar",
    role: "CrossFit & Conditioning Specialist",
    badge: "COACH 04 · CADRE",
    discipline: "High-Intensity Functional Training",
    image: "/images/trainers/nilesh-patekar.png",
    ogImage: "/images/trainers/og/nilesh-patekar-card.jpg",
    ogPhoto: "/images/trainers/og/nilesh-patekar.jpg",
    quote: "Your body is your primary equipment. Master it across every domain.",
    bio: "Nilesh thrives in the intensity of the CrossFit arena. His programming is a brutal but beautifully orchestrated symphony of gymnastics, Olympic weightlifting, and monostructural cardio. He is dedicated to building well-rounded, adaptive athletes who can tackle any physical challenge with work capacity to spare. Nilesh’s classes are a crucible where limitations are burned away.",
    certifications: ["CrossFit Level 2 Trainer", "Olympic Weightlifting Coach"],
    experience: "7+ Years",
    instagram: "https://instagram.com/19hoursfitness",
  },
  {
    id: "swapnil-pendhare",
    number: "05",
    name: "Swapnil Pendhare",
    role: "Transformation & Hypertrophy Coach",
    badge: "COACH 05 · CADRE",
    discipline: "Body Recomposition & Nutrition",
    image: "/images/trainers/swapnil-pendhare.png",
    ogImage: "/images/trainers/og/swapnil-pendhare-card.jpg",
    ogPhoto: "/images/trainers/og/swapnil-pendhare.jpg",
    quote: "Transformation is 20% in the gym and 80% in your habits.",
    bio: "Swapnil is the architect of radical physical transformations. He combines targeted hypertrophy training with exacting nutritional protocols to strip body fat and reveal hard, striated muscle. He understands the psychological warfare of dieting and provides the relentless accountability required to see a recomp protocol through to the end. Under his guidance, members achieve the physiques they once thought impossible.",
    certifications: ["Precision Nutrition Level 1", "Body Recomposition Specialist"],
    experience: "9+ Years",
    instagram: "https://instagram.com/19hoursfitness",
  },
  {
    id: "prasad-mestry",
    number: "06",
    name: "Prasad Mestry",
    role: "Elite Personal Trainer",
    badge: "COACH 06 · CADRE",
    discipline: "Strength Periodization & Mobility",
    image: "/images/trainers/prasad-mestry.png",
    ogImage: "/images/trainers/og/prasad-mestry-card.jpg",
    ogPhoto: "/images/trainers/og/prasad-mestry.jpg",
    quote: "Longevity in fitness comes from lifting heavy and moving freely.",
    bio: "Prasad bridges the gap between raw strength and fluid mobility. As an elite personal trainer, he tailors highly individualized periodization cycles that account for a client's unique biomechanical constraints. He believes that strength without mobility is a liability. His clients learn to control their bodies through full ranges of motion, bulletproofing joints while systematically increasing load.",
    certifications: ["Master Personal Trainer", "Functional Range Conditioning (FRC)"],
    experience: "11+ Years",
    instagram: "https://instagram.com/19hoursfitness",
  },
  {
    id: "gaurav-satam",
    number: "07",
    name: "Gaurav Satam",
    role: "Functional & Strength Specialist",
    badge: "COACH 07 · CADRE",
    discipline: "Athletic Performance & Core Stability",
    image: "/images/trainers/gaurav-satam.png",
    ogImage: "/images/trainers/og/gaurav-satam-card.jpg",
    ogPhoto: "/images/trainers/og/gaurav-satam.jpg",
    quote: "Power generates from the core. Build the foundation first.",
    bio: "Gaurav focuses on building bulletproof foundations. His expertise lies in athletic performance training, with a heavy emphasis on multi-planar movement, core stability, and functional power generation. He trains clients to move like athletes—explosively, efficiently, and without pain. From kettlebell flows to plyometrics, Gaurav's training creates bodies that look great and perform even better in the real world.",
    certifications: ["Functional Movement Systems (FMS)", "Athletic Performance Coach"],
    experience: "6+ Years",
    instagram: "https://instagram.com/19hoursfitness",
  },
];

